AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  deep-sort-people-counter

  SAM Template for implementing deep-sort-people-counter

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Metadata:
  AWS::ServerlessRepo::Application:
    Name: deep-sort-people-counter
    SemanticVersion: 0.0.1
    Author: Gandhinath Swaminathan
    Description: Object Tracker application using Deep Sort

Resources:
  DeepSortPeopleCounterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: application/
      Handler: app.main
      Runtime: python3.7
      MemorySize: 2048
      Timeout: 180

Parameters:
  threshold: 
    Type: Number
    Description: People detection model threshold
    Default: 0.30

  people_detection_model:
    Type: String
    Description: People detection model
    Default: ssd_512_resnet50_voc_v02

  reid_tracking_model:
    Type: String
    Description: People re-identification model
    Default: reid_model_v1_v02

  detection_input_size_h:
    Type: Number
    Description: Detection model input size height (actual shape will be [1, 3, detection_input_size_h, detection_input_size_w])
    Default: 512

  detection_input_size_w:
    Type: Number
    Description: Detection model input size width(actual shape will be [1, 3, detection_input_size_h, detection_input_size_w])
    Default: 512

  tracking_input_size_h:
    Type: Number
    Description: Tracking model input size height (actual shape will be [1, 3, tracking_input_size_h, tracking_input_size_w])
    Default: 256

  tracking_input_size_w:
    Type: Number
    Description: Tracking model input size width(actual shape will be [1, 3, tracking_input_size_h, tracking_input_size_w])
    Default: 128

  batch_size:
    Type: Number
    Description: Model batch size
    Default: 1
  
  person_class_index:
    Type: Number
    Description: Person class index based on the model
    Default: 14
  
  tracking_max_dist:
    Type: Number
    Description: Euclidean distance separated from the previous distribution
    Default: 0.5
  
  tracking_min_confidence:
    Type: Number
    Description: Confidence threshold
    Default: 0.3
  
  tracking_nms_max_overlap:
    Type: Number
    Description: Threshold for non-max supression
    Default: 0.8
  
  tracking_max_iou_distance:
    Type: Number
    Description: Threshold for Area of Intersection/Area of Union of actual & predicted bounding box
    Default: 0.7
 
  tracking_max_age:
    Type: Number
    Description: Number of frames to survive before assigning new identity
    Default: 70

  tracking_n_init:
    Type: Number
    Description: Number of frames before assigning identity or relinquishing it
    Default: 5

  tracking_nn_budget:
    Type: Number
    Description: Number of samples
    Default: 20

  top_y:
    Type: Number
    Description: Top Y co-ordinate to indicate the entry/exit point
    Default: 200

  bottom_y:
    Type: Number
    Description: Bottom Y co-ordinate to indicate the entry/exit point
    Default: 800

  aws_iot_endpoint_url:
    Type: String
    Description: AWS IoT data endpoint url
    Default: <>-ats.iot.<>.amazonaws.com

  enable_overlay:
    Type: Number
    Description: Enable video overlay
    Default: 1
    AllowedValues:
      - 0
      - 1

  enable_mqtt:
    Type: Number
    Description: Enable data sink for MQTT
    Default: 1
    AllowedValues:
      - 0
      - 1

  enable_kinesis:
    Type: Number
    Description: Enable video sink for Kinesis video stream
    Default: 1
    AllowedValues:
      - 0
      - 1

Outputs:
  DeepSortPeopleCounterFunction:
    Description: "People Counter Lambda Function ARN"
    Value: !GetAtt DeepSortPeopleCounterFunction.Arn
  DeepSortPeopleCounterFunctionIamRole:
    Description: "Implicit IAM Role created for People Directional Counter function"
    Value: !GetAtt DeepSortPeopleCounterFunction.Arn